name: Publish Plugin

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Publish to JetBrains Marketplace
        env:
          SIGN_PLUGIN_CERTIFICATE_CHAIN: ${{ secrets.SIGN_PLUGIN_CERTIFICATE_CHAIN }}
          SIGN_PLUGIN_PRIVATE_KEY: ${{ secrets.SIGN_PLUGIN_PRIVATE_KEY }}
          SIGN_PLUGIN_PRIVATE_KEY_PASSWORD: ${{ secrets.SIGN_PLUGIN_PRIVATE_KEY_PASSWORD }}
          PLUGIN_PUBLISH_TOKEN: ${{ secrets.PLUGIN_PUBLISH_TOKEN }}
        run: ./gradlew clean signPlugin publishPlugin
